title: redsnw
description:
author: ""
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

emailjs:
  service_id: "service_sgi6pkq"
  template_id: "template_2478vxs"
  public_key: "KjS7j2_VWzlUJ1kj1"
  to_email: "victor.khatibi@student.ksgvf.se"
